- rebench.conf
The missing `-G` was a mistake.
The results on [ReBenchDB](https://rebench.stefan-marr.de/compare/SOMns/ab38ad697262d4b96c61567d7e4e1ca83dc226c0/9adf0650b60f9b1a6a2fee61bc03177387763833) clearly shows the impact of that change for `TruffleSOM-interp`.
Most micro benchmarks benefit from avoiding interference from compilation.
The macro startup benchmarks can suffer, because they run long enough that they reach some compiled code.
/cc @sophie-kaleba
> Make sure TruffleSOM-interp is actually the interpreter

- src/trufflesom/interpreter/nodes/ContextualNode.java
This avoids having more profiles than necessary. It should be a single type for the materialized frames, and thus, a static profile is sufficient.
Relates to https://github.com/smarr/SOMns/issues/361
@fniephaus thanks for the hint!
> Turn frameType profile into a static

- build.xml
- som
This updates Truffle.
The main changes are:
- renaming of `graal.` flags to `polyglot.engine.`
- introduction of language agnostic inlining, which currently causes quite some slow downs. See https://rebench.stefan-marr.de/compare/SOMns/bbcdedb5db68449f637a0b3929cdb8f79df08391/b3f4c76f3a0e1bc8964030aa77f2d8499d5acd31 The report compares the version with enabled language agnostic inlining (base, blue), and the version without (change, orange). Thus, we disable language agnostic inlining for now.
> Update Truffle to pre-20.3

- .gitlab-ci.yml
- build.xml
- som
- added --no-libgraal flag to disable use of libgraal
- only compile libgraal-jdk for the compile target
- use of interpreter-only implies we don’t need libgraal
- the jar target doesn’t use libgraal-jdk, but truffle-libs, which makes it better for use in CI
- for ci and testing, truffle-lib is just fine. So, on Travis, we are avoid compiling libgraal
> Use libgraal as standard compiler

- .gitlab-ci.yml
- rebench.conf
Enable reporting of results to ReBenchDB, which reports it to GitHub.
> Report benchmark completion to ReBenchDB

- som
Using the `--igv` option currently throws an exception: `Exception in thread "main" java.lang.IllegalArgumentException: Could not find option with name engine.Dump.`
The `Dump` option was not concerned by the new engine flags. Reverting to the `-Dgraal.` flag solves the issue.
> revert Dpolyglot.engine.Dump option to Dgraal.Dump

- .gitignore
- src/trufflesom/interpreter/nodes/specialized/whileloops/WhileCache.java
- src/trufflesom/primitives/basics/EqualsEqualsPrim.java
- src/trufflesom/primitives/basics/EqualsPrim.java
- src/trufflesom/primitives/basics/UnequalsPrim.java
- src/trufflesom/vm/Universe.java
- src/trufflesom/vmobjects/SObject.java
This PR removes the instantiation of the classes `True` and `False` from the code base.
It's not needed, because we use Java's `true` and `false` to represent the only instances of these classes there are.
The PR also does a bit of maintenance:
- remove unused code from Object (left over from object model changes for #47)
- add more things to .gitignore
- fix some comment formatting
> Avoid need for instances of SObject for Booleans

- .gitignore
- .gitlab-ci.yml
- build.xml
- rebench.conf
This generates a native image for TruffleSOM with a bytecode interpreter.
> Add target for a bytecode native image

- .gitlab-ci.yml
- build.xml
- rebench.conf
- src/trufflesom/vm/Universe.java
- src/trufflesom/vm/VmSettings.java
This should reduce a little bit the noise in measurements, and allows me to more clearly see impact on interpreter performance.
This adds the `-Dno.jit=true` flag to build.xml and the `-Dsom.jitCompiler=false` flag to SOM.
> Benchmark native interpreters preferably

- src/trufflesom/compiler/MethodGenerationContext.java
- src/trufflesom/compiler/Parser.java
- src/trufflesom/compiler/ParserAst.java
- src/trufflesom/compiler/ParserBc.java
- src/trufflesom/compiler/bc/BytecodeGenerator.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/compiler/bc/Disassembler.java
- src/trufflesom/interpreter/SNodeFactory.java
- src/trufflesom/interpreter/bc/Bytecodes.java
- src/trufflesom/interpreter/nodes/FieldNode.java
- src/trufflesom/interpreter/nodes/MessageSendNode.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- src/trufflesom/interpreter/nodes/specialized/IntIncrementNode.java
- src/trufflesom/interpreter/objectstorage/FieldAccessorNode.java
- src/trufflesom/interpreter/objectstorage/StorageLocation.java
- src/trufflesom/vm/Universe.java
This PR introduces 5 new bytecodes, and adds optimizations avoid common patterns in the generated bytecode sequences.
The bytecode optimizes the common sequence of `[POP,] PUSH_ARGUMENT (0, 0), RETURN_LOCAL`.
Since it's the implicit sequence at the end of many methods, it turned up frequently in the bytecode profile.
It's generated directly in the parser. It is also used for normal methods (not block methods) that end in an explicit `^ self`.
Another common bytecode sequence is `PUSH_CONSTANT 1, SEND +`.
The `SEND -` version was not as common, but still visible in the weighted profiles.
For symmetry, I introduced the `INC` and `DEC` bytecodes, which optimize adding or subtracting 1 from an integer.
They are generated directly in the parser.
One of the common sequences generated by the …
> Optimize frequently used bytecode sequences

- src/trufflesom/compiler/MethodGenerationContext.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/interpreter/Primitive.java
- src/trufflesom/interpreter/nodes/MessageSendNode.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- src/trufflesom/interpreter/nodes/dispatch/CachedExprNode.java
- src/trufflesom/interpreter/nodes/dispatch/SuperDispatchNode.java
- src/trufflesom/interpreter/nodes/dispatch/UninitializedDispatchNode.java
- src/trufflesom/interpreter/nodes/literals/BlockNode.java
- src/trufflesom/interpreter/objectstorage/ObjectLayout.java
- src/trufflesom/primitives/Primitives.java
- src/trufflesom/primitives/basics/NewObjectPrim.java
- src/trufflesom/vm/Shell.java
- src/trufflesom/vm/Universe.java
- src/trufflesom/vmobjects/SInvokable.java
- src/trufflesom/vmobjects/SObject.java
Super sends where not yet previously quickened in the bytecode interpreters.
Now, we use the `Q_SEND` bytecode in the same way as normal sends, and initialize the quickening node on first execution.
Further, this PR optimizes object creation by caching the `ObjectLayout` for a class.
This requires some further changes to expose the `NewObjectPrim` at the lexical location where it is used to be able to benefit from the caching. Previously, there would have only been the primitive itself, which would have been megamorphic since it saw all object instantiations.
To expose the lexical stability, the new prim is now integrated with the dispatch chains. We can't use the existing eager primitive mechanism, because it does not account for inheritance, which is of course an issue with `new` being …
> Quicken Super Sends and optimize Object Instantiation

- src/trufflesom/compiler/MethodGenerationContext.java
- src/trufflesom/compiler/Parser.java
- src/trufflesom/compiler/ParserAst.java
- src/trufflesom/compiler/ParserBc.java
- src/trufflesom/compiler/Variable.java
- src/trufflesom/compiler/bc/BytecodeGenerator.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/interpreter/Invokable.java
- src/trufflesom/interpreter/Primitive.java
- src/trufflesom/interpreter/bc/Bytecodes.java
- src/trufflesom/interpreter/nodes/ArgumentReadNode.java
- src/trufflesom/interpreter/nodes/ExpressionNode.java
- src/trufflesom/interpreter/nodes/FieldNode.java
- src/trufflesom/interpreter/nodes/GlobalNode.java
- src/trufflesom/interpreter/nodes/SequenceNode.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- src/trufflesom/interpreter/nodes/dispatch/CachedExprNode.java
- src/trufflesom/interpreter/nodes/dispatch/SuperDispatchNode.java
- src/trufflesom/interpreter/nodes/dispatch/UninitializedDispatchNode.java
- src/trufflesom/interpreter/nodes/literals/BlockNode.java
- src/trufflesom/interpreter/nodes/literals/LiteralNode.java
- src/trufflesom/primitives/basics/NewObjectPrim.java
- src/trufflesom/primitives/reflection/GlobalPrim.java
- src/trufflesom/vm/NotYetImplementedException.java
- src/trufflesom/vmobjects/SInvokable.java
This PR adds an optimization that inlines trivial methods like accessors, but also the NewObjectPrim into the dispatch chain.
Support is added for bytecode on AST interpreters.
The bytecode interpreter also uses the trivial AST nodes instead of a separate bytecode loop for the trivial methods.
There are a few other changes:
- NotYetImplemented has now constructor with message
- we error when multiple locals have the same name
- the BytecodeGen is now static
- fixed equality if locals
- refactored things to use the Variable objects for lookups, instead of symbols
- rewrite how bytecode matching, tracking, and optimizations are done to provide a more high-level infrastructure and helpers
> Optimize access, and other trivial methods

- src/trufflesom/compiler/MethodGenerationContext.java
- src/trufflesom/compiler/ParserBc.java
- src/trufflesom/compiler/bc/BytecodeGenerator.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/compiler/bc/Disassembler.java
- src/trufflesom/interpreter/Invokable.java
- src/trufflesom/interpreter/Method.java
- src/trufflesom/interpreter/bc/Bytecodes.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- src/trufflesom/interpreter/nodes/literals/BlockNode.java
This PR implements bytecode-level inlining of `#ifTrue:`, `#ifFalse:`, `#ifTrue:ifFalse:`, and `#ifFalse:ifTrue:`.
As always, inlining is a somewhat hairy exercise, and this is no different here.
I rely on much of the infrastructure for the AST interpreters, but need to handle the bytecodes separately.
To make the inlining work easily, I now exclude all block methods from the trivial optimizations. This way, I don't need special handling and bytecode reconstruction for those.
Mandelbrot seems to suffer a little in performance from this. As far as I can tell, this is an issue with boxing elimination, which doesn't trigger as completely as before.
> Add bytecode-level inlining of ifTrue/ifFalse* messages

- src/trufflesom/interpreter/nodes/bc/BinaryPrimitiveWrapper.java
- src/trufflesom/interpreter/nodes/bc/TernaryPrimitiveWrapper.java
- src/trufflesom/interpreter/nodes/bc/UnaryPrimitiveWrapper.java
- src/trufflesom/interpreter/nodes/specialized/whileloops/WhileWithDynamicBlocksNode.java
- src/trufflesom/primitives/EmptyPrim.java
- src/trufflesom/primitives/arithmetic/AdditionPrim.java
- src/trufflesom/primitives/arithmetic/DividePrim.java
- src/trufflesom/primitives/arithmetic/GreaterThanPrim.java
- src/trufflesom/primitives/arithmetic/LessThanOrEqualPrim.java
- src/trufflesom/primitives/arithmetic/LessThanPrim.java
- src/trufflesom/primitives/arithmetic/LogicAndPrim.java
- src/trufflesom/primitives/arithmetic/ModuloPrim.java
- src/trufflesom/primitives/arithmetic/MultiplicationPrim.java
- src/trufflesom/primitives/arithmetic/RemainderPrim.java
- src/trufflesom/primitives/arithmetic/SqrtPrim.java
- src/trufflesom/primitives/arithmetic/SubtractionPrim.java
- src/trufflesom/primitives/basics/EqualsPrim.java
- src/trufflesom/primitives/basics/HashPrim.java
- src/trufflesom/primitives/basics/IntegerPrims.java
- src/trufflesom/primitives/basics/StringPrims.java
- src/trufflesom/primitives/basics/UnequalsPrim.java
This PR adds the `@TruffleBoundary` to make compilation work.
> Native image >21.1 black lists many operations from compilation

- .github/workflows/ci.yml
- awfy-test.conf
- som
- src/trufflesom/compiler/Disassembler.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/compiler/bc/Disassembler.java
- src/trufflesom/interpreter/nodes/dispatch/CachedDnuNode.java
- src/trufflesom/primitives/basics/SystemPrims.java
- src/trufflesom/vm/Universe.java
- src/trufflesom/vm/VmSettings.java
By adding the AWFY benchmarks to CI, I caught a few issues.
- setter methods were optimized if the last thing was a field assignment, but anything before it was ignored (fixed)
- Havlak would run out of stack with exceptions that are completely unrelated
To improve debugging, I added a few niceties:
- print stack trace on `#doesNotUnderstand:` using the `-dnu` option in the launcher
- print bytecode after parsing using the `-di` option on the launcher
The Havlak issue is fixed by giving the VM more stack when we assume that Havlak is run.
The size of stack change is only done for Havlak since I don't know what the impact is.
> Add AWFY Test runs to CI, add Stack Trace support, and bytecode dumping, and fix incorrect setter optimization

- .gitlab-ci.yml
- src/trufflesom/compiler/ParserBc.java
- src/trufflesom/compiler/bc/BytecodeGenerator.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/compiler/bc/Disassembler.java
- src/trufflesom/interpreter/bc/Bytecodes.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
This PR introduces inlining of basic while loops.
It directly inlines the blocks if and only if they are lexical blocks.
This needs a new backwards jump bytecode and, because much more inlining happens now, it needs a new set of jump bytecodes that take two bytes for the jump offset.
Originally, I only introduced the backwards jump to save one bit of address range, and don't have to deal with negative jumps.
This still seems beneficial, and a useful tactic, also to identify bugs.
Thus, I added the JUMP2* bytecodes, which use two bytes for address, essentially an unsigned short.
Though, because we don't know before writing the offset how long it is going to be, I gave all jump bytecodes length 3.
This means, I don't need to deal with shifting things around.
At run-time, the normal JUMP …
> Add inlining of #whileTrue:/whileFalse: loops

- src/trufflesom/compiler/ClassGenerationContext.java
- src/trufflesom/compiler/Disassembler.java
- src/trufflesom/compiler/Parser.java
- src/trufflesom/primitives/Primitives.java
- src/trufflesom/vm/Universe.java
- src/trufflesom/vmobjects/SClass.java
This removes the use of a dedicated SArray to store the methods of a class.
We already used a hashmap before, now, the LinkedHashMap is the only data structure to keep the methods.
This simplifies code a little, and was an opportunity to remove old cruft.
Performance-wise, it's not quite clear whether this is positive or not.
A lookup over a 1 or 2 element array is hard to beat...
> Use LinkedHashMap as only storage for method in class

- src/trufflesom/compiler/MethodGenerationContext.java
- src/trufflesom/compiler/ParserBc.java
- src/trufflesom/compiler/bc/BytecodeGenerator.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/compiler/bc/Disassembler.java
- src/trufflesom/interpreter/bc/Bytecodes.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
Replicate the optimization from the AST to avoid materializing the context of blocks that do not access it.
> Add PUSH_BLOCK_NO_CTX

- src/trufflesom/interpreter/Method.java
- src/trufflesom/interpreter/Primitive.java
- src/trufflesom/primitives/arrays/AtPrim.java
- src/trufflesom/primitives/arrays/AtPutPrim.java
- src/trufflesom/primitives/arrays/CopyPrim.java
- src/trufflesom/primitives/arrays/DoPrim.java
- src/trufflesom/primitives/arrays/PutAllNode.java
- src/trufflesom/primitives/arrays/ToArgumentsArrayNode.java
- src/trufflesom/primitives/basics/LengthPrim.java
- src/trufflesom/vm/Universe.java
- src/trufflesom/vmobjects/SArray.java
- src/trufflesom/vmobjects/SClass.java
This PR ports fixes and improvements of storage strategy handling from SOMns to TruffleSOM.
There are also a few improvements here.
Main improvements:
- use storage directly to determine storage type. This could have potentially the drawback of more complex guards, because there's an extra read of the class of the storage. And it indeed seems to hurt startup performance a little.
- more eagerly transition to object storage if it looks like that's the best option (avoids sticking too long with a partially empty strategy)
- order checks so that we transition to object storage as soon as there's no other option left
Generic maintenance:
- remove hash from primitive and method names
- reduce some of the code duplication in AtPutPrim
@fniephaus this fixes my performance issues, I believe …
> Improve Array Storage strategies based on SOMns

- .github/workflows/ci.yml
- src/trufflesom/compiler/MethodGenerationContext.java
- src/trufflesom/compiler/Parser.java
- src/trufflesom/compiler/ParserAst.java
- src/trufflesom/compiler/ParserBc.java
- src/trufflesom/compiler/bc/BytecodeGenerator.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/interpreter/nodes/GlobalNode.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- src/trufflesom/primitives/arithmetic/AdditionPrim.java
- src/trufflesom/primitives/arithmetic/MultiplicationPrim.java
- src/trufflesom/primitives/arithmetic/SubtractionPrim.java
This PR updates the core-lib with various new tests.
It fixes super semantics where the parser was still being buggy.
If makes sure that the AST interpreter sends `#unknownGlobal:` and `#escapedBlock:` to the outer self.
And it makes sure we return long values from arithmetic operations even after an overflow, because otherwise things like `Array>>#new:` break in unexpected ways.
It also updates the URL for Eclipse so that GitHub actions are green again.
> Update core-lib and fix super sends and #unknownGlobals/#escapedBlock handling

- src/trufflesom/compiler/MethodGenerationContext.java
- src/trufflesom/compiler/Parser.java
- src/trufflesom/compiler/bc/BytecodeGenerator.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/compiler/bc/Disassembler.java
- src/trufflesom/interpreter/nodes/ArgumentReadNode.java
- src/trufflesom/interpreter/nodes/FieldNode.java
- src/trufflesom/interpreter/nodes/GlobalNode.java
- src/trufflesom/interpreter/nodes/ReturnNonLocalNode.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- src/trufflesom/interpreter/nodes/specialized/IntToDoInlinedLiteralsNode.java
- tests/trufflesom/tests/AstInliningTests.java
- tests/trufflesom/tests/BytecodeMethodTests.java
- tests/trufflesom/tests/BytecodeTestSetup.java
- tests/trufflesom/tests/TruffleTestSetup.java
This adds PySOM's test, but ignores most of them for the moment, because the two implementations don't yet behave consistently.
There a few more fixes:
- remove `None` from symbol list
- fix stack depth of `jump_on_*_pop` bytecodes
- some cleanups
> Add tests from PySOM and various minor fixes

- src/trufflesom/compiler/ParserAst.java
- src/trufflesom/interpreter/nodes/GlobalNode.java
- src/trufflesom/interpreter/nodes/MessageSendNode.java
- src/trufflesom/interpreter/nodes/specialized/IfTrueIfFalseInlinedLiteralsNode.java
- src/trufflesom/primitives/Primitives.java
- tests/trufflesom/tests/AstInliningTests.java
This PR fixes missing inlining for `#||` and `#&&` with literal blocks.
It also adds inlining for `#ifFalse:ifTrue:`, and synchronizes the so far ignored AST inlining tests with PySOM, mostly around the increment nodes.
> Inline #||, #&&, and #ifFalse:ifTrue: and sync increment node tests with PySOM

- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
Use a transferToInterpreter and throw an exception afterwards.
This might perhaps give the compiler an extra incentive to generate good code...
> Exclude default branch in interpreter loop from compilation

- src/trufflesom/compiler/Parser.java
- src/trufflesom/compiler/bc/BytecodeGenerator.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/compiler/bc/Disassembler.java
- src/trufflesom/interpreter/bc/Bytecodes.java
- src/trufflesom/interpreter/nodes/GlobalNode.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- src/trufflesom/vm/Universe.java
This PR removes the second pass over the bytecode to compute the stack hight.
This doesn't seem to have any measurable performance impact, but avoids a bit of code duplication.
I also tried using a lookup array as in PySOM, but no significant performance difference.
However, this PR also uses symbols to check for specialization opportunities, instead of using string comparison.
For some reason, this turns out to be a bit slower.
Don't really understand why, but it might lead to issue in the symbol table? Haven't investigated it further.
Though, I'll leave it in, since it seems a semantically useful change.
> Remove second bytecode pass for stack hight and use symbols for checks

- src/trufflesom/compiler/ClassGenerationContext.java
- src/trufflesom/compiler/MethodGenerationContext.java
- src/trufflesom/compiler/Parser.java
- src/trufflesom/compiler/ParserAst.java
- src/trufflesom/compiler/ParserBc.java
- src/trufflesom/compiler/Variable.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/interpreter/nodes/GlobalNode.java
- src/trufflesom/interpreter/nodes/dispatch/CachedDnuNode.java
- src/trufflesom/primitives/Primitives.java
- src/trufflesom/primitives/basics/StringPrims.java
- src/trufflesom/vm/Shell.java
- src/trufflesom/vm/SymbolTable.java
- src/trufflesom/vm/Universe.java
- src/trufflesom/vmobjects/SAbstractObject.java
- tests/trufflesom/tests/AstInliningTests.java
- tests/trufflesom/tests/BytecodeBlockTests.java
- tests/trufflesom/tests/BytecodeMethodTests.java
- tests/trufflesom/tests/BytecodeTestSetup.java
- tests/trufflesom/tests/TruffleTestSetup.java
This extracts the symbol table from the universe.
The main reason to keep the change is to reduce a little the various responsibilities of the universe.
There doesn't seem to be any positive performance impact from this change though.
> Make symbol table global, to avoid indirection to universe

- src/trufflesom/compiler/ParserBc.java
- src/trufflesom/compiler/bc/BytecodeGenerator.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- tests/trufflesom/tests/BytecodeMethodTests.java
This PR inlines literal blocks for and/or messages.
It also moves the `addLiteralIfAbsent()` calls into the emit*Send methods to avoid adding unnecessary literals to methods.
This change is only for the bytecode interpreter.
Overall performance seems to suffer on the startup metric.
Though, the interpreter-only benchmarks seem to benefit a little.
Steady state performance seems largely unaffected. NBody (-14%), Richards (-7%), and Towers (-10%) seem to see reductions in run time for the interpreter only execution.
https://rebench.stefan-marr.de/compare/TruffleSOM/c3388f263550dc18ca5a703bfbda2a029546b3a3/c2dffba0800176fb267fcbf46b3b70858370c93f#micro-somsom-SomSom-native-interp-bc
> Implement inlining for #and:/#&&/#or:#||

- .gitlab-ci.yml
- rebench.conf
Run benchmarks on all three benchmarking machines.
Currently only building the native images is done in parallel, because we don't have support for packaging and distributing TruffleSOM.
This means, each machine builds is own local version of libgraal and co. Though, it's relatively quick. So, will leave it like this.
> Parallelize benchmarks

- src/trufflesom/compiler/Lexer.java
- tests/trufflesom/compiler/LexerTests.java
- add lexer source coordinate tests
Co-authored-by: @HumphreyHCB
> Fix initial value for lastLineEnd in Lexer

- .gitlab-ci.yml
- .graal-git-rev
- build.xml
- rebench.conf
This adds profiling of the native image interpreters.
This will allow us to track interpreter performance in more detail.
Also remove an old script not used/needed.
> Add continuous profiling to benchmark setup

- .gitlab-ci.yml
- build.xml
- src/trufflesom/interpreter/SomLanguage.java
Truffle Guest Safepoints have a performance impact on most microbenchmarks, and thus, I initially disabled them.
Though, it's part of the Truffle feature set, so, it should be enabled. It's also used by TruffleRuby to implement its features. Thus, having enabled is good for comparability.
However, I should remember it, especially when comparing to PySOM.
> Enable Truffle Guest Safepoints

- rebench.conf
They where not yet benchmarked. This fixes it.
> Fix executable names for EE SomSom benchmarks

- rebench.conf
- src/trufflesom/compiler/Lexer.java
- src/trufflesom/compiler/Parser.java
- src/trufflesom/interpreter/objectstorage/ObjectLayout.java
- src/trufflesom/interpreter/objectstorage/StorageLocation.java
- tests/trufflesom/intepreter/objectstorage/BasicStorageTester.java
- with the updated core-lib, it's now explicit that we do GC between benchmark iterations
- avoid unnecessary object for peek operation in lexer
- remove redundant code to load `Unsafe`
- remove `layout` from `StorageLocation` to make it independent. We can't really cache them though, because we still have the `fieldIndex` as well as the other "raw access index". The `fieldIndex` is needed for fallbacks, so, there might be some special cases where it could be avoided, but not generally.
> Update core-lib and other minor improvements

- .classpath
- som
- src/tools/nodestats/AstNode.java
- src/tools/nodestats/NodeStatisticsCollector.java
- src/tools/nodestats/NodeStatsTool.java
- src/tools/nodestats/SubTree.java
- src/tools/nodestats/YamlReport.java
- src/trufflesom/compiler/MethodGenerationContext.java
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/interpreter/LexicalScope.java
- src/trufflesom/interpreter/Method.java
- src/trufflesom/interpreter/SomLanguage.java
- src/trufflesom/interpreter/nodes/ExpressionNode.java
- src/trufflesom/vm/Universe.java
- src/trufflesom/vm/VmSettings.java
- tests/tools/nodestats/AstNodeTests.java
- tests/tools/nodestats/StaticNodeStructureTests.java
This adds a tool that collects some basic statistics about nodes after running a SOM application/benchmark.
It gets all `RootNode`s and traverses the ASTs to collect the details.
The output written to a YAML file, and looks roughly like this:
```
report:
node-numbers:
- com.oracle.truffle.api.impl.DefaultDirectCallNode:                  { score: 8615 }
- trufflesom.interpreter.nodes.GenericMessageSendNode:                { score: 8583 }
- trufflesom.interpreter.nodes.dispatch.UninitializedDispatchNode:    { score: 8556 }
- trufflesom.interpreter.nodes.dispatch.CachedDispatchNode:           { score: 8329 }
- trufflesom.interpreter.nodes.ArgumentReadNode$LocalArgumentReadNode:{ score: 6823 }
- trufflesom.interpreter.nodes.literals.IntegerLiteralNode:           { score: 5431 } …
```
> Add Tool to Collect Statistics about AST Nodes

- rebench.conf
- remove `system fullGC` call from `Hash?Test` classes, don't need it, just slows things down
> Add benchmark to measure AST vs BC GC overhead

- src/trufflesom/interpreter/nodes/dispatch/DispatchGuard.java
Instead of an `instanceof` check, which has complex semantics, just read the class and check that. Tiny optimization/simplification.
> Use exact class check in dispatch guard

- rebench.conf
The results are too noisy, and I am not looking at that data anymore.
The "steady" benchmarks still give an indication, so, major regressions should not be missed.
> Do not measure startup for Graal on HotSpot

- build.xml
Previously, the G1 garbage collector was not enabled for the EE builds, it seems to have some impact on interpreter speed, but is a better GC for the AST-heavy benchmarks.
For absolute peak performance, one may need to reconsider.
> Enable G1 on Linux EE Builds and Fix macOS Builds 

- .github/workflows/ci.yml
- rebench.conf
SomParse loads a bunch of SOM files, and benchmarks that.
It's useful to get an impression of what impact the parser changes have.
The changes to the SomSom benchmark seems to have minimal impact, if at all.
> Added SomParse benchmark, and make SomSom not measure parsing

- src/trufflesom/primitives/Primitives.java
- src/trufflesom/primitives/basics/EqualsEqualsPrim.java
- src/trufflesom/primitives/basics/UnequalUnequalPrim.java
- src/trufflesom/primitives/basics/UnequalsPrim.java
The `#==` primitive can be simplified by using the generic pointer comparison to avoid the overhead of the different cases in the interpreter.
> Simplify #== primitive and split #<> and #~= primitives to simplify them

- src/bd/inlining/InlinableNodes.java
- src/bd/inlining/Inliner.java
- src/trufflesom/compiler/ParserAst.java
- tests/bd/inlining/InliningTests.java
This is mostly a cleanup change.
It also reorders the check for inlining opportunities after the handling of super messages, since we do have the assumption (and assert) that it's not a super send.
> Use array instead of list for inliner, which we need in most cases anyway

- .gitignore
- src/bd/inlining/Inliner.java
- src/trufflesom/compiler/Variable.java
- src/trufflesom/interpreter/SNodeFactory.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- src/trufflesom/interpreter/objectstorage/FieldAccessorNode.java
- src/trufflesom/interpreter/supernodes/IncLocalVariableNode.java
- src/trufflesom/interpreter/supernodes/IncNonLocalVariableNode.java
- src/trufflesom/interpreter/supernodes/IntIncFieldNode.java
- src/trufflesom/interpreter/supernodes/IntIncLocalVariableNode.java
- src/trufflesom/interpreter/supernodes/IntIncNonLocalVariableNode.java
- src/trufflesom/interpreter/supernodes/IntIncrementNode.java
- src/trufflesom/interpreter/supernodes/IntUninitIncFieldNode.java
- src/trufflesom/interpreter/supernodes/UninitIncFieldNode.java
- tests/trufflesom/supernodes/IncrementOpTests.java
- tests/trufflesom/tests/AstInliningTests.java
This adds the following nodes:
- `Inc[Non]LocalVariableNode`: can have an arbitrary value expression
- have `IntIncFieldNode` and `IncFieldNode`: the first has a constant integer (was previously called IncFieldNode), and a new second one that takes an arbitrary expression (now called IncFieldNode)
@OctaveLarose please review.
> Handle more situations where we read and then set a variable/field

- src/trufflesom/interpreter/nodes/FieldNode.java
- src/trufflesom/interpreter/supernodes/IncLocalVariableNode.java
- src/trufflesom/interpreter/supernodes/IncNonLocalVariableNode.java
- tests/trufflesom/supernodes/IncrementOpTests.java
- tests/trufflesom/supernodes/SquareTests.java
String concatenation is black listed on for GraalVM 22.0 native image compilation.
This also fixes an incorrect guard for the IncNonLocal* case.
> Put string concatenation behind truffle boundary

- src/trufflesom/primitives/basics/SystemPrims.java
This PR implements the primitives for the System class:
- #gcStats: returns an array with GC count and total GC time in milliseconds, based on the Java `GarbageCollectorMXBean`
- #totalCompilationTime: returns an integer with the total time spend compiling, based on that Java `CompilationMXBean`
/cc @OctaveLarose here the primitives for TruffleSOM to get extra statistics.
> Add the #gcStats and #totalCompilationTime primitives to System class

- som
With this change, we can use `-EG ./some/path/to/graal`.
The path needs to contain `bin/java`.
> Add support for an explicit path on the EG flag, which points to the graal to be used

- build.xml
Update Truffle to the latest version.
This unfortunately, introduces a performance regression.
Tracked via https://github.com/oracle/graal/issues/4690 and locally via #150.
The PR also changes the default behavior of dumping graphs for methods to store them in files, which is generally more useful, for instance to share the graphs.
> Truffle update, and dump IGV graphs to file per default

- src/trufflesom/interpreter/nodes/AbstractMessageSendNode.java
- src/trufflesom/interpreter/nodes/GenericMessageSendNode.java
- src/trufflesom/interpreter/nodes/MessageSendNode.java
- src/trufflesom/interpreter/nodes/UninitializedMessageSendNode.java
- src/trufflesom/vmobjects/SInvokable.java
These changes enable the inlining of `getNumberOfArguments()` in bytecode loop, and avoid the extra indirection via the symbol in other cases.
Microbenchmarks show some nice gains on the bytecode interpreter: https://rebench.stefan-marr.de/compare/TruffleSOM/bace2c4d3ebe38d0b0ba8d491c1fa071f7a9ace2/f5bc03835789dd12bf4f67b9308434a99ec4bab2
> Enable inlining of getNumberOfArguments()

- src/trufflesom/interpreter/nodes/specialized/NotMessageNode.java
- src/trufflesom/primitives/arithmetic/AdditionPrim.java
- src/trufflesom/primitives/arithmetic/ArithmeticPrim.java
- src/trufflesom/primitives/arithmetic/BitXorPrim.java
- src/trufflesom/primitives/arithmetic/DividePrim.java
- src/trufflesom/primitives/arithmetic/DoubleDivPrim.java
- src/trufflesom/primitives/arithmetic/GreaterThanOrEqualPrim.java
- src/trufflesom/primitives/arithmetic/GreaterThanPrim.java
- src/trufflesom/primitives/arithmetic/LessThanOrEqualPrim.java
- src/trufflesom/primitives/arithmetic/LessThanPrim.java
- src/trufflesom/primitives/arithmetic/LogicAndPrim.java
- src/trufflesom/primitives/arithmetic/ModuloPrim.java
- src/trufflesom/primitives/arithmetic/MultiplicationPrim.java
- src/trufflesom/primitives/arithmetic/RemainderPrim.java
- src/trufflesom/primitives/arithmetic/SubtractionPrim.java
- src/trufflesom/primitives/arrays/AtPrim.java
- src/trufflesom/primitives/arrays/AtPutPrim.java
- src/trufflesom/primitives/arrays/NewPrim.java
- src/trufflesom/primitives/basics/BlockPrims.java
- src/trufflesom/primitives/basics/EqualsEqualsPrim.java
- src/trufflesom/primitives/basics/EqualsPrim.java
- src/trufflesom/primitives/basics/IntegerPrims.java
- src/trufflesom/primitives/basics/LengthPrim.java
- src/trufflesom/primitives/basics/StringPrims.java
- src/trufflesom/primitives/basics/UnequalUnequalPrim.java
- src/trufflesom/primitives/basics/UnequalsPrim.java
- src/trufflesom/primitives/reflection/MethodPrims.java
- src/trufflesom/primitives/reflection/ObjectPrims.java
This is a bit of preparation for experiments with the upcoming Truffle Operations DSL.
This PR turns some of the specializations needed into static methods, simply by adding the `static` keyword. It doesn't change anything else.
This is expected to be performance neutral on Graal and native image.
As far as I can tell, there's only noise: https://rebench.stefan-marr.de/compare/TruffleSOM/f5bc03835789dd12bf4f67b9308434a99ec4bab2/5c530df24ddd2d9702e8eebc252d8f567b8e1057
> Make specializations static for Operations DSL

- build.xml
- som
Periodic update
And some minor changes to the build setup, introducing `ant compile-for-dev` which doesn't compile libgraal and thus, is much faster.
> Update Truffle and MX

- .gitlab-ci.yml
- build.xml
- src/trufflesom/interpreter/bc/Bytecodes.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- src/trufflesom/interpreter/objectstorage/FieldAccessorNode.java
- src/trufflesom/vmobjects/SAbstractObject.java
This PR introduces some changes into the bytecode loop to improve the interpreted performance on native image.
Most relevant changes are:
- check objects for being null before the loop
- move error and node-creation cut behind a `@InliningCutoff`
In addition, instead of reading the bytecode length from the array, encode it directly in the switch/case. This seems to have only minimal impact, if at all.
Also add a `-Ddbg=true` flag to the native-image ant script, to allow debugging of the native image compiler.
> Improve bytecode loop performance

- build.xml
- som
- src/trufflesom/primitives/basics/StringPrims.java
The latest version of Graal/Truffle seems to want version 19.
This update seems to cause some performance regressions.
The bytecode interpreter seems to see 8% longer run times on the SomSom benchmarks.
Json (on the JIT+AST) seems to suffer a little, which might be the additional boundary.
They bytecode interpreter speed seems to be impacted.
> Update JDK to version 19

- src/bdt/inlining/InlinableNodes.java
- src/bdt/inlining/Inliner.java
- src/trufflesom/compiler/Parser.java
- src/trufflesom/interpreter/EscapedBlockException.java
- src/trufflesom/interpreter/ReturnException.java
- src/trufflesom/interpreter/bc/RespecializeException.java
- src/trufflesom/interpreter/nodes/specialized/IfMessageNode.java
- src/trufflesom/interpreter/nodes/specialized/IntDownToDoMessageNode.java
- src/trufflesom/interpreter/nodes/specialized/IntToDoMessageNode.java
- src/trufflesom/interpreter/nodes/specialized/whileloops/WhileFalsePrimitiveNode.java
- src/trufflesom/interpreter/nodes/specialized/whileloops/WhilePrimitiveNode.java
- src/trufflesom/interpreter/nodes/specialized/whileloops/WhileTruePrimitiveNode.java
- src/trufflesom/primitives/basics/NewObjectPrim.java
- src/trufflesom/primitives/reflection/AbstractSymbolDispatch.java
- src/trufflesom/primitives/reflection/MethodPrims.java
- src/trufflesom/primitives/reflection/PerformInSuperclassPrim.java
- src/trufflesom/primitives/reflection/PerformWithArgumentsInSuperclassPrim.java
- src/trufflesom/primitives/reflection/PerformWithArgumentsPrim.java
- using `@Cached` and `@Shared` instead of fields
- avoid unnecessary helper methods
- add explicit limits
- handle non-serializable field warnings
> Minor improvements preparing for Object Inlining

- .gitlab-ci.yml
- rebench.conf
- src/trufflesom/interpreter/nodes/specialized/IfInlinedLiteralNode.java
- src/trufflesom/interpreter/nodes/specialized/IfMessageNode.java
- src/trufflesom/interpreter/nodes/specialized/IfNilInlinedLiteralNode.java
- src/trufflesom/interpreter/nodes/specialized/IfNotNilInlinedLiteralNode.java
- src/trufflesom/interpreter/nodes/specialized/IfTrueIfFalseInlinedLiteralsNode.java
- src/trufflesom/interpreter/nodes/specialized/IfTrueIfFalseMessageNode.java
- src/trufflesom/primitives/arithmetic/SqrtPrim.java
- src/trufflesom/primitives/basics/IntegerPrims.java
- src/trufflesom/primitives/reflection/AbstractSymbolDispatch.java
This change adopts the Truffle version with object inlining.
This doesn't really use object inlining, except for a few cases of inlined profiles.
For the moment, this needs to disable enterprise edition, because it doesn't have the object inlining yet.
> Update to Truffle with Object Inlining

- src/trufflesom/primitives/arithmetic/AdditionPrim.java
- src/trufflesom/primitives/basics/EqualsPrim.java
- it’s only defined in String
- there’s no hint that it should behave differently in Symbol which is a subclass
- so, we really should just consider the string content when comparing #foobar = ‘foobar’
- `#a + #b == #ab` should hold
> The #= on Symbol and String should be symmetric

- build.xml
- som
There seems to be quite a bit of a performance regression for the AST interpreter:
https://rebench.dev/TruffleSOM/compare/d59b30fcb9f5a4a01786370e5553c9196dae9027..3f4596b30ef0e048c5a8c144e6ed5d3aace4dbdc#micro-startup-TruffleSOM-native-interp-ast
Some benchmarks have 8% or 11% longer run times.
> Update Truffle to version from 2023-01-27

- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
This gives up to 19% in tight loops on the bytecode interpreter.
https://rebench.dev/TruffleSOM/compare/ab5d088e282dbd5f85b9f407ca0163dfebd33a2a..2b64d5a99b96f35f401796ab8004798c75f4c227#micro-somsom-SomSom-native-interp-bc
/cc @OctaveLarose This is something that should be part of your baseline please :)
> Extract the exceptional cases out of the send bytecode handlers

- som
- src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/compiler/bc/Disassembler.java
- src/trufflesom/interpreter/Method.java
- src/trufflesom/interpreter/nodes/ExpressionNode.java
- src/trufflesom/interpreter/nodes/FieldNode.java
- src/trufflesom/interpreter/nodes/GlobalNode.java
- src/trufflesom/interpreter/nodes/SequenceNode.java
- src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- tests/tools/nodestats/StaticNodeStructureTests.java
- tests/trufflesom/tests/BytecodeTestSetup.java
- tests/trufflesom/tests/OptimizeTrivialTests.java
This PR makes sure that we do not accidentally try to create a trivial method for a block needed in another block.
For that to work, we would need to have a trivial field read node, which supports reading from a context.
While that would be easy to implement, we can do that another time.
This PR tries to make sure we avoid the issue, and test for it.
It also tries to make sure that we support trivial blocks with a field read in the bytecode interpreter, where we are currently missing this optimization.
@OctaveLarose, that's the other issue that came up on your branch.
> Blocks with a field read nested in a block are not yet supported

- som
- src/bdt/inlining/NodeVisitorUtil.java
- src/bdt/inlining/ScopeAdaptationVisitor.java
Only the splitting operations require the old AST to be intact. For the bytecode inlining, we also really don’t need to copy the AST, we just need to traverse it.
> Avoid copying the AST for non-splitting operations

- .github/workflows/ci.yml
- mx.trufflesom/mx_trufflesom.py
- mx.trufflesom/suite.py
- som
- src/trufflesom/src/trufflesom/Launcher.java
- src/trufflesom/src/trufflesom/vm/Universe.java
- tests/trufflesom/tests/BasicInterpreterTests.java
- tests/trufflesom/tests/SomTests.java
- tests/trufflesom/tests/TruffleTestSetup.java
This moves the main method out of Universe into a Launcher class to avoid class dependencies in the main context, i.e., non-Truffle code.
This also reverts the `--no-native` work-around from the last PR.
And, finally, perhaps most importantly, the som launcher is now adapted to use the module path.
> Update Truffle to latest version

- .github/workflows/ci.yml
- .gitlab-ci.yml
- README.md
- mx.trufflesom/mx_trufflesom.py
- som
With a recent change, mx broke my setup and changed priorities of where to take JAVA_HOME from.
With this change, we move the labsjdk and mx loading into the launcher behind the `./som --setup` option/command.
This also revise a bit where options are shown, to better group things.
And, we now rely on the `python3` binary... for the launcher to avoid issues when Python 2 is still present.
> Move building support to launcher script and cleanup launcher options

- mx.trufflesom/suite.py
- som
This required changes in the module path of the `som` launcher script since the SDK is now split into multiple jars.
> Update Graal to August 12th

- .github/workflows/ci.yml
- .gitlab-ci.yml
- mx.trufflesom/mx_trufflesom.py
- mx.trufflesom/suite.py
The update required to add an explicit dependency to `TRUFFLE_TEST`.
I also noted that the tests were broken and didn't properly set the right property for the interpreter...
The PR also removes the use of `--no-native` which is brittle and breaks things, because it forcibly removes stuff, but doesn't really seem to make much of a difference when it comes to compile time savings.
As part of identifying the now needed `TRUFFLE_TEST` dependency, [Tomas](https://graalvm.slack.com/archives/CNQSB2DHD/p1701172925817229?thread_ts=1701022365.626539&cid=CNQSB2DHD) also suggested an alternative option:
```patch
diff --git a/mx.trufflesom/mx_trufflesom.py b/mx.trufflesom/mx_trufflesom.py
index c0bd455a..97e393f3 100644
--- a/mx.trufflesom/mx_trufflesom.py
+++ b/mx.trufflesom/mx_trufflesom.py
@@ -4,6 …
```
> Update Truffle and fix issues with tests

- src/trufflesom/src/trufflesom/compiler/MethodGenerationContext.java
- src/trufflesom/src/trufflesom/compiler/ParserAst.java
- src/trufflesom/src/trufflesom/compiler/Variable.java
- src/trufflesom/src/trufflesom/interpreter/nodes/ArgumentReadNode.java
- src/trufflesom/src/trufflesom/interpreter/supernodes/IntIncrementNode.java
- src/trufflesom/src/trufflesom/interpreter/supernodes/LocalFieldStringEqualsNode.java
- src/trufflesom/src/trufflesom/interpreter/supernodes/NonLocalFieldStringEqualsNode.java
- src/trufflesom/src/trufflesom/interpreter/supernodes/StringEqualsNode.java
- tests/trufflesom/supernodes/StringEqualsTests.java
- tests/trufflesom/tests/AstInliningTests.java
This PR is based on https://github.com/SOM-st/TruffleSOM/pull/185, and extracts the supernodes for the comparison with literal strings:
- `"someString" = var` and `var = "someString"`
- the various variations with locals, arguments, non-locals, and fields
- fields for local and non-local access to `self`
> Add supernode for comparing a literal string

- .github/workflows/ci.yml
- mx.trufflesom/env
- mx.trufflesom/graal
- mx.trufflesom/suite.py
- som
- improve error reporting for missing graal-enabled java binaries
- update GitHub actions
> Add env file to easily use Java version of Graal

- som
Otherwise, it will execute mx in the wrong working directory.
> Use BASE_DIR as working directory when requesting the graalvm-home

- .gitlab-ci.yml
- mx.trufflesom/mx_trufflesom.py
- rebench.conf
- som
- use native-image binary when GraalVM is given to build-native
- use module path for native image compilation
- update `GRAALEE_HOME` and `JAVA_HOME`
- reset `graal` repo based on suite.py
- fix native image deprecation warnings
- disable G1 by default on EE
> Reenable benchmarking on EE, or rather Oracle GraalVM now

- rebench.conf
This updates the core-lib to https://github.com/SOM-st/SOM/pull/121
and adds the benchmarks to the rebench.conf file.
> Add more interpreter microbenchmarks

- .gitlab-ci.yml
- mx.trufflesom/suite.py
- som
- src/trufflesom/src/trufflesom/interpreter/nodes/GenericMessageSendNode.java
- src/trufflesom/src/trufflesom/interpreter/nodes/GenericMessageSendNodeWrapper.java
- src/trufflesom/src/trufflesom/interpreter/nodes/SequenceNode.java
- src/trufflesom/src/trufflesom/interpreter/nodes/dispatch/DispatchChain.java
- src/trufflesom/src/trufflesom/interpreter/nodes/literals/LiteralNode.java
- src/trufflesom/src/trufflesom/primitives/reflection/PerformWithArgumentsPrim.java
- tests/trufflesom/supernodes/StringEqualsTests.java
- tests/trufflesom/tests/AstInliningTests.java
- tests/trufflesom/tests/OptimizeTrivialTests.java
This adds the M2 machine for benchmarking.
Other changes:
- update Truffle
- removes use of `NodeCost` since that was/is going to be deprecated in Truffle 24.1
- use `MatcherAssert.assertThat()` to handle deprecation
- request use of mx version 7.27.2
- use sha512 checksum for Checkstyle dependency
> Added zullie1 to GitLab benchmarking setup

- .gitlab-ci.yml
This is only for the GitLabCI setup.
It also updates the JDK to version 22.
This PR also adds the scripting to use asdf to install GraalVM and JDK.
> Update GraalVM EE to oracle-graalvm-ea-jdk-23.0.0-ea.14

- src/trufflesom/src/trufflesom/compiler/bc/BytecodeGenerator.java
- src/trufflesom/src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/src/trufflesom/compiler/bc/Disassembler.java
- src/trufflesom/src/trufflesom/interpreter/bc/Bytecodes.java
- src/trufflesom/src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- src/trufflesom/src/trufflesom/primitives/basics/BlockPrims.java
- tests/trufflesom/tests/BytecodeBlockTests.java
PE fails with multiple values for the Queens benchmark.
This is a work around, but works for the moment.
Not sure what the underlying issue is. It's surprising and indicates something else is wrong.
Also fix some DSL issues around polymorphism.
> Fix issues with PE: move context level for non-local returns to bytecode node

- mx.trufflesom/mx_trufflesom.py
- mx.trufflesom/suite.py
- som
As I understand it, the extra libraries are used for the Truffle Unchained mode.
> Update LabsJDK and add the various libraries needed by Truffle these days

- src/trufflesom/src/trufflesom/interpreter/objectstorage/FieldAccessorNode.java
- src/trufflesom/src/trufflesom/interpreter/objectstorage/StorageLocation.java
This PR fixes the reading of fields that are not yet set, but have been seen to eventually be double or long primitive values.
The implementation in the storage location would need to throw an `UnexpectedResultException` for `nil` values, which did not lead to a respecialization, but just a transfer to interpreter.
> Fix reading nil from long and double fields, and update core-lib

- src/trufflesom/src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/src/trufflesom/interpreter/bc/Bytecodes.java
- src/trufflesom/src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- tests/trufflesom/tests/BytecodeBlockTests.java
- tests/trufflesom/tests/BytecodeMethodTests.java
- tests/trufflesom/tests/BytecodeTestSetup.java
Only change the jump bytecode when it's not already the 2-byte version.
And various minor improvements.
> Fix jump patching

- .gitlab-ci.yml
- mx.trufflesom/suite.py
- rebench.conf
This neatly cuts the overall CI time in half.
> Use yuria4 for benchmarking

- .gitignore
- .gitlab-ci.yml
- som
- src/trufflesom/src/trufflesom/compiler/Lexer.java
- src/trufflesom/src/trufflesom/interpreter/objectstorage/FieldAccessorNode.java
- src/trufflesom/src/trufflesom/vm/Classes.java
- src/trufflesom/src/trufflesom/vmobjects/SObject.java
The launcher wasn't properly using the environment variables.
Think the changed version is more what I would expect.
Field access in FieldAccessorNode had a few issues:
- most importantly, they never went to a megamorphic case, so, would have endless chains
- there was unnecessary re-specialization when encountering objects with an outdated object layout
This change should be performance neutral, but may not be: https://rebench.dev/TruffleSOM/compare/1bc7250d08356fe9ea7cb8525064231cd39c4e4e..58b446652be9a6281b462f9b8cea1c8c2b5bc5ec
> Fix GRAAL_HOME/JVMCI_BIN handling in `som` and fix field access implementation

- .github/workflows/ci.yml
- mx.trufflesom/mx_trufflesom.py
- mx.trufflesom/suite.py
- src/trufflesom/src/trufflesom/interpreter/nodes/ContextualNode.java
- src/trufflesom/src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
This PR is mostly GHA maintenance, but also has a code change:
- have only a single frameType profile object
Maintenance:
- change Eclipse download URL since mirrors don't have the version any more (newer versions do get stuck on Github Actions for unknown reason)
- apply black formatting to mx suite
- setup black and pylint on GitHub actions
> Fix style gate on GitHub Actions and use only single frameType profile object

- src/trufflesom/src/trufflesom/compiler/MethodGenerationContext.java
- src/trufflesom/src/trufflesom/compiler/ParserAst.java
- src/trufflesom/src/trufflesom/compiler/Variable.java
- src/trufflesom/src/trufflesom/interpreter/nodes/LocalVariableNode.java
- src/trufflesom/src/trufflesom/interpreter/nodes/NonLocalVariableNode.java
- src/trufflesom/src/trufflesom/interpreter/supernodes/LocalVariableReadSquareWriteNode.java
- src/trufflesom/src/trufflesom/interpreter/supernodes/LocalVariableSquareNode.java
- src/trufflesom/src/trufflesom/interpreter/supernodes/NonLocalVariableReadSquareWriteNode.java
- src/trufflesom/src/trufflesom/interpreter/supernodes/NonLocalVariableSquareNode.java
- tests/trufflesom/supernodes/SquareTests.java
This PR adds support for the basic multiplication of a variable with itself for local and non-local variables, i.e.:
- `local * local`
- `| l | [ l * l ]`
It also supports multiplication and assigning result to local/non-local variables:
- `b := l * l`
This is taking a bit of https://github.com/SOM-st/TruffleSOM/pull/185 to integrate directly.
This PR should benefit the following benchmarks:
- Mandelbrot (mostly this one I believe)
- NBody
- PageRank
- CD
> Add Square supernodes

- .gitlab-ci.yml
- mx.trufflesom/suite.py
- rebench.conf
Update Graal/Truffle to version of 2024-11-16 and update the rebench and GitLab CI configuration to the renaming of `machines` to `tags`.
> Truffle Update, and ReBench compatibility

- src/trufflesom/src/trufflesom/compiler/ParserBc.java
- src/trufflesom/src/trufflesom/compiler/bc/BytecodeGenerator.java
- src/trufflesom/src/trufflesom/compiler/bc/BytecodeMethodGenContext.java
- src/trufflesom/src/trufflesom/compiler/bc/Disassembler.java
- src/trufflesom/src/trufflesom/interpreter/bc/Bytecodes.java
- src/trufflesom/src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
- src/trufflesom/src/trufflesom/interpreter/nodes/specialized/IfNilNotNilInlinedLiteralNode.java
- src/trufflesom/src/trufflesom/interpreter/nodes/specialized/IfNotNilNilInlinedLiteralNode.java
- src/trufflesom/src/trufflesom/primitives/Primitives.java
- tests/trufflesom/tests/AstInliningTests.java
- tests/trufflesom/tests/BytecodeMethodTests.java
This implements inlining in the AST and bytecode interpreters.
> Implement inlining for various `#ifNil:*` variants

- mx.trufflesom/suite.py
There might be a performance benefit for some minor things, not clear: https://rebench.dev/TruffleSOM/compare/4dda1a1c83c7da01b9966fd953ca0ac1ab86a62c..fa5c2777d8478de07c6257cb7b02fdc08986acdf
> Update Truffle to version of 2025-05-17

- .github/workflows/ci.yml
- integration-tests-ast.yml
- integration-tests-bc.yml
- src/trufflesom/src/trufflesom/primitives/arithmetic/BitXorPrim.java
- src/trufflesom/src/trufflesom/primitives/arithmetic/GreaterThanOrEqualPrim.java
- src/trufflesom/src/trufflesom/primitives/arithmetic/LessThanOrEqualPrim.java
- src/trufflesom/src/trufflesom/primitives/arrays/AtPutPrim.java
- src/trufflesom/src/trufflesom/primitives/basics/EqualsPrim.java
- src/trufflesom/src/trufflesom/primitives/basics/IntegerPrims.java
- src/trufflesom/src/trufflesom/primitives/basics/SystemPrims.java
- src/trufflesom/src/trufflesom/primitives/reflection/ObjectPrims.java
This PR adds the support for running the SOM integration tests as introduced with https://github.com/SOM-st/SOM/pull/128 and https://github.com/SOM-st/SOM/pull/129.
It also fixes a number of smaller issues.
However, many issues remain unresolved, often because SOM does not yet specify what the expected behavior should be.
> Add running of integration tests and fix some issues
