SOM-st/TruffleSOM

.factorypath, .gitmodules, build.xml, som, src/som/compiler/Lexer.java, src/som/compiler/MethodGenerationContext.java, src/som/compiler/Parser.java, src/som/compiler/SourcecodeCompiler.java, src/som/interpreter/Method.java, src/som/interpreter/nodes/LocalVariableNode.java, src/som/interpreter/nodes/NonLocalVariableNode.java, src/som/interpreter/nodes/specialized/IfMessageNode.java, src/som/interpreter/nodes/specialized/IfTrueIfFalseMessageNode.java, src/som/interpreter/nodes/specialized/whileloops/WhileCache.java, src/som/primitives/arrays/PutAllNode.java, src/som/primitives/reflection/AbstractSymbolDispatch.java, src/som/vmobjects/SObject.java, src/tools/SourceCoordinate.java
This adopts the new unified Graal/Truffle repo and updates to the latest version.
This implies changes to:
- update launcher
- update submodules (rename mxtool to mx)
- fix issues in the lexer
- fix issue in LocalVariableNode
- update use of some APIs, no complete replacement of deprecated APIs yet
=> Update to latest Truffle version

.checkstyle_checks.xml, .factorypath, build.xml, src/som/compiler/MethodGenerationContext.java, src/som/interpreter/SomLanguage.java, src/som/interpreter/nodes/NonLocalVariableNode.java, src/som/interpreter/nodes/dispatch/SuperDispatchNode.java, src/som/interpreter/nodes/specialized/BooleanInlinedLiteralNode.java, src/som/interpreter/nodes/specialized/IfInlinedLiteralNode.java, src/som/interpreter/nodes/specialized/IfTrueIfFalseInlinedLiteralsNode.java, src/som/interpreter/nodes/specialized/whileloops/WhileInlinedLiteralsNode.java, src/som/interpreter/objectstorage/StorageLocation.java, src/som/vm/Universe.java, tests/som/tests/BasicInterpreterTests.java, tests/som/tests/SomTests.java
This change updates Truffle and with it mx, checkstyle, BlackDiamonds.
The most important change is the switch from using `PolyglotEngine` to `Context`, and with it the other necessary changes of using for instance `@Option` to pass options/settings to the context.
=> Update Truffle to v.1.0.0 RC2

.travis.yml, build.xml, som
'som' script had the old namespace, so I changed this to the new namespace 'trufflesom.vm.Universe'.
I also integrated the proposed test from @smarr  calling the som script.
This is my first pull request to TruffleSOM. Any tips are appreciated. Maybe I should have made 3 PRs?
=> Follow up on namespace change

.travis.yml, build.xml, src/trufflesom/compiler/MethodGenerationContext.java, src/trufflesom/compiler/Parser.java, src/trufflesom/compiler/Variable.java, src/trufflesom/interpreter/SArguments.java, src/trufflesom/interpreter/SNodeFactory.java, src/trufflesom/interpreter/nodes/ArgumentReadNode.java, tests/trufflesom/tests/BasicInterpreterTests.java, tests/trufflesom/tests/SomTests.java
This does a bit of infrastructure maintenance and updates the core lib to the latest version.
=> Update core lib and make arguments assignable

.gitlab-ci.yml, build.xml, som
This is a sync with SOMns so that maintenance is simpler, and that stuff actually works again.
=> Sync build/launch setup with SOMns, fix ReBench config

src/trufflesom/primitives/Primitives.java
Report primitives to structural probe.
=> Primitive reporting got lost

.travis.yml, src/trufflesom/compiler/Lexer.java, src/trufflesom/primitives/basics/StringPrims.java
These changes adopt https://github.com/SOM-st/SOM/pull/30 and also update core-lib.
And set the Ubuntu version to Trusty to be sure we have a Java 8.
=> Added String isWhiteSpace, isLetters, isDigits primitives and \0 escape code

build.xml, rebench.conf, src/trufflesom/interpreter/nodes/dispatch/UninitializedDispatchNode.java, src/trufflesom/vmobjects/SArray.java
- fixes misuse of profiles in `SArray`
- improve compilation of uninitialized dispatch nodes
- fix settings of startup microbenchmarks
- add ant target to avoid checking dependencies
@sophie-kaleba, this one might be interesting for you, happy to discuss the performance fixes
=> Various minor fixes, including benchmark settings, and performance of arrays

.gitlab-ci.yml, rebench.conf
We need to adapt to the lowered core frequency.
This PR also updates the core-lib.
=> Update Benchmark Setup for latest ReBench Version

tests/trufflesom/tests/BasicInterpreterTests.java
Integrates changes of https://github.com/SOM-st/SOM/pull/54 and earlier.
=> Added tests for uninitialized locals and empty blocks

.classpath, src/trufflesom/compiler/Parser.java, src/trufflesom/primitives/basics/IntegerPrims.java
This is a fix and update to support https://github.com/SOM-st/SOM/pull/58
@sophie-kaleba SOM-java already had the fixes, though, you may not need these changes.
=> Added support for Integer>>#min: and fix some issues with BigIntegers

src/trufflesom/primitives/basics/IntegerPrims.java
Update to https://github.com/SOM-st/SOM/pull/59
=> Add missing big int support for as32bit* and abs prims

src/trufflesom/primitives/basics/DoublePrims.java, src/trufflesom/primitives/basics/IntegerPrims.java, src/trufflesom/primitives/basics/SystemPrims.java, tests/trufflesom/tests/BasicInterpreterTests.java
This PR does a bit of minor maintenance, but the key part are the added primitives to run SomSom:
- Double class>>#fromString:
- System>>#errorPrint:
- System>>#errorPrintln:
- System>>#loadFile:
- System>>#printStackTrace:
- Integer>>#asDouble
=> Add primitives for SomSom

src/trufflesom/compiler/MethodGenerationContext.java, src/trufflesom/compiler/Parser.java, src/trufflesom/compiler/ParserBc.java, src/trufflesom/compiler/bc/BytecodeGenerator.java, src/trufflesom/compiler/bc/BytecodeMethodGenContext.java, src/trufflesom/compiler/bc/Disassembler.java, tests/trufflesom/tests/BytecodeBlockTests.java, tests/trufflesom/tests/BytecodeMethodTests.java, tests/trufflesom/tests/BytecodeTestSetup.java
This PR adds tests as added to PySOM via https://github.com/SOM-st/PySOM/pull/26 and https://github.com/SOM-st/PySOM/pull/27.
=> Fix dup/pop/pop optimization and add tests

src/trufflesom/interpreter/nodes/LocalVariableNode.java, src/trufflesom/interpreter/nodes/NonLocalVariableNode.java
This is convenience for the LSP.
=> Added getters for the language server to access locals

.gitlab-ci.yml, build.xml, rebench.conf, som, src/trufflesom/interpreter/Invokable.java, src/trufflesom/interpreter/SomLanguage.java, src/trufflesom/primitives/arithmetic/GreaterThanPrim.java, src/trufflesom/primitives/basics/EqualsPrim.java, src/trufflesom/vmobjects/SInvokable.java, tests/trufflesom/tests/BytecodeMethodTests.java, tests/trufflesom/tests/SomTests.java
- add Flight Recorder profiling option in `som`
- use gitlab dependencies to start benchmarks slightly earlier
This uses a hack to disable Truffle's guest safepoints, which we currently don't use.
=> Update Truffle/mx and minor maintenance

.gitlab-ci.yml, build.xml, rebench.conf, src/trufflesom/interpreter/SomLanguage.java, src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java, src/trufflesom/vmobjects/SInvokable.java
This sets up AST and BC interpreters, compiled with GraalVM Enterprise Edition and G1 as GC, for benchmarking.
=> Setup EE Interpreters

som, src/trufflesom/interpreter/nodes/MessageSendNode.java, src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java
Performance-wise it might not be perfect. On EE numbers look unchanged. On CE, things might be slightly slower.
=> Some smaller changes, mostly simplifications

src/trufflesom/interpreter/Types.java, src/trufflesom/interpreter/nodes/ExpressionNode.java, src/trufflesom/interpreter/nodes/FieldNode.java, src/trufflesom/interpreter/nodes/SequenceNode.java, src/trufflesom/interpreter/nodes/literals/BlockNode.java, src/trufflesom/interpreter/nodes/specialized/whileloops/WhileWithStaticBlocksNode.java
- be more explicit, and avoid unnecessary use of TypesGen
- remove the not really used type specializations for SBlock and SObject, and replace them with straight casts
- don't have `executeAllButLast` be in a separate method, doesn't seem to gain us anything
=> Minor cleanups

som, src/tools/nodestats/NodeStatsCLI.java, src/tools/nodestats/NodeStatsTool.java, src/trufflesom/vm/Universe.java
This adds the Truffle-based options.
=> Make NodeStatsTool compatible with Truffle launchers

.classpath
This fixes the Eclipse project after removing the dependency on the Black Diamonds project.
=> Fix Eclipse classpath

src/trufflesom/interpreter/nodes/NonLocalVariableNode.java
This way, `determineContext()` is only called once per specialization.
- also remove guard code that's now simplified
- use `@Shared` just hoping that it would work (doesn't currently, but might in the future, then it would be only called once)
- simplify some of the other small bits
(Don't need a transferToInterpreter, it's already done by setFrameSlotKind)
Performance impact of this change is unclear, slightly positive at best.
/cc @OctaveLarose thought might be interesting to see `@Bind` in action.
=> Use `@Bind` to avoid multiple determineContext calls in NonLocalVarNodes

src/trufflesom/interpreter/Primitive.java
Truffle Hosted Inlining improves interpreter performance by 20-25% for the AST interpreter, and 10-17% for the bytecode interpreter:
https://rebench.stefan-marr.de/compare/TruffleSOM/8685dbc4909391ef380b83a7ce247e64d3cafc7f/5403861e8e0036ab443b6a36b9b85d169acec5cf
=> Update Truffle to version that brings Truffle's Hosted Inlining

src/trufflesom/primitives/basics/SystemPrims.java
This extends the gcStats primitive to include an approximate number of allocated bytes for the current thread in the returned array.
=> Add allocated bytes to gcStats

src/trufflesom/compiler/MethodGenerationContext.java, src/trufflesom/compiler/ParserAst.java, src/trufflesom/interpreter/nodes/AbstractMessageSendNode.java, src/trufflesom/interpreter/nodes/specialized/IfInlinedLiteralNode.java, src/trufflesom/interpreter/nodes/specialized/IsNilIfTrue.java, src/trufflesom/interpreter/supernodes/LocalVarReadUnaryMsgWriteNode.java, src/trufflesom/interpreter/supernodes/NonLocalVarReadUnaryMsgWriteNode.java
- supernode for updating local based on message send to that local
- optimize `isNil ifTrue:` basically like `ifNil:`
This gives on the List benchmark:
- -19% CE int
- -22% EE int
=> Add supernodes for List benchmark

rebench.conf
Update the core-lib with the AWFY benchmarks.
=> Add CD and Havlak to benchmarking

.github/workflows/ci.yml, .gitlab-ci.yml, mx.trufflesom/lint.sh, mx.trufflesom/suite.py
This is an interims update, which works without major changes, only needs a hack to work around a bug that was fixed later.
=> Update Truffle to version of Mai

.github/workflows/ci.yml, .gitlab-ci.yml, mx.trufflesom/mx_trufflesom.py, mx.trufflesom/suite.py, som
Fix the GitLab CI setup and `som` launcher script to make sure that we get the right and compatible LabsJDK version.
=> Update Truffle and make sure we get the right JVMCI version

src/trufflesom/src/trufflesom/interpreter/nodes/dispatch/AbstractDispatchNode.java, src/trufflesom/src/trufflesom/primitives/arrays/PutAllNode.java, src/trufflesom/src/trufflesom/primitives/basics/BlockPrims.java, src/trufflesom/src/trufflesom/primitives/reflection/IndexDispatch.java, tests/trufflesom/tests/SomTests.java
- use `@Cached`
- use `@NeverDefault`
- add missing tests to SomTests
=> Add missing tests to SomTests, and minor changes

.gitlab-ci.yml, mx.trufflesom/suite.py
Update the dependencies together so that things keep working.
=> Truffle and Oracle GraalEE update

src/trufflesom/src/trufflesom/compiler/MethodGenerationContext.java, src/trufflesom/src/trufflesom/compiler/Parser.java, src/trufflesom/src/trufflesom/compiler/ParserAst.java, src/trufflesom/src/trufflesom/compiler/ParserBc.java, src/trufflesom/src/trufflesom/compiler/Variable.java, src/trufflesom/src/trufflesom/compiler/bc/BytecodeMethodGenContext.java, src/trufflesom/src/trufflesom/interpreter/nodes/AbstractMessageSendNode.java, src/trufflesom/src/trufflesom/interpreter/nodes/ArgumentReadNode.java, src/trufflesom/src/trufflesom/interpreter/nodes/GenericMessageSendNode.java, src/trufflesom/src/trufflesom/interpreter/nodes/GlobalNode.java, src/trufflesom/src/trufflesom/interpreter/nodes/LocalVariableNode.java, src/trufflesom/src/trufflesom/interpreter/nodes/MessageSendNode.java, src/trufflesom/src/trufflesom/interpreter/nodes/NonLocalVariableNode.java, src/trufflesom/src/trufflesom/interpreter/nodes/UninitializedMessageSendNode.java, src/trufflesom/src/trufflesom/interpreter/nodes/bc/BytecodeLoopNode.java, src/trufflesom/src/trufflesom/interpreter/nodes/specialized/IntDownToDoInlinedLiteralsNode.java, src/trufflesom/src/trufflesom/interpreter/nodes/specialized/IntToDoInlinedLiteralsNode.java, src/trufflesom/src/trufflesom/vm/SymbolTable.java, tests/trufflesom/tests/AstInliningTests.java, tests/trufflesom/tests/AstTestSetup.java, tests/trufflesom/tests/BytecodeBlockTests.java, tests/trufflesom/tests/BytecodeMethodTests.java, tests/trufflesom/tests/OptimizeTrivialTests.java
These are minor optimizations/cleanups.
Though, they are not expected to have a performance impact.
=> Reduce number of Symbols created and remove blocks from literal array after inlining

.gitlab-ci.yml, mx.trufflesom/suite.py
- performance is noisy https://rebench.dev/TruffleSOM/compare/9642da55243f05a815907c37f4b2728d7ebf9926..1f4e2034a5c7fd5e07ace4a3f6a89c7b309754aa
- fixed a JAVA_HOME issue for building tools
=> Update Truffle to version of 2024-08-23

.gitlab-ci.yml, src/trufflesom/src/trufflesom/interpreter/supernodes/compare/LocalArgGreaterThanInt.java, src/trufflesom/src/trufflesom/interpreter/supernodes/compare/LocalArgLessThanInt.java, src/trufflesom/src/trufflesom/interpreter/supernodes/compare/LocalFieldStringEqualsNode.java, src/trufflesom/src/trufflesom/interpreter/supernodes/inc/IncFieldWithExpNode.java, src/trufflesom/src/trufflesom/primitives/arithmetic/AdditionPrim.java, src/trufflesom/src/trufflesom/primitives/arithmetic/SubtractionPrim.java, tests/trufflesom/tests/SplittingTests.java
=> Minor improvements

.github/workflows/ci.yml, .gitlab-ci.yml, mx.trufflesom/suite.py
This PR updates Truffle and various other dependencies.
=> Update Truffle dependency, GraalVM, JDK, and PyLint on GHA
